<?php
/**
 * Created by PhpStorm.
 * User: CK
 * Date: 2017/10/12
 * Time: 11:00
 */
namespace Modules\Pc\Tests;

use Modules\Pc\Tests\Common\V1\ApiTestCase;

class IndexTest extends ApiTestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->init();
    }

    public function readyApiParams()
    {
        $params['goodscategory_list'] = [
            'method' => 'get',
            'uri' => '/pc/goodscategory-list',
            'params' => [

            ],
        ];
        $params['messageannounce_list'] = [
            'method' => 'get',
            'uri' => '/pc/messageannounce-list',
            'params' => [

            ],
        ];
        return $params;
    }
    /**
     * 商城商品的分类
     * @Author CK
     */
    public function testGoodsCategoryListTest()
    {
        $this->apiTest($this->params['goodscategory_list']);
    }
    /**
     * 商城商品的公告
     * @Author CK
     */
    public function testMessageAnnounceListTest()
    {
        $this->apiTest($this->params['messageannounce_list']);
    }

}