<?php
/**
 * Created by PhpStorm.
 * User: caohan
 */
namespace Modules\Backend\Tests;

use Modules\Backend\Tests\Common\BackendTestCase;

class ArticleTest extends BackendTestCase
{
    public $complete_url = false;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->init();
    }

    public function readyApiParams()
    {
        $params = [];
        $params['ArticleTypeAdd'] = [
            'method' => 'post',
            'uri' => '/backend/articletype-add',
            'params' => [
                'type_name'=>'unit顶级',
                'parent_id'=>'0',
            ],
        ];

        $params['ArticleTypeList'] = [
            'method' => 'get',
            'uri' => '/backend/articletype-list',
            'params' => [],
        ];

        $params['ArticleTypeEdit'] = [
            'method' => 'post',
            'uri' => '/backend/articletype-edit',
            'params' => [
                'type_id'=>'1',
                'type_name'=>'unit-update',
                'parent_id'=>'0',
            ],
        ];

        $params['ArticleTypeList'] = [
            'method' => 'get',
            'uri' => '/backend/articletype-list',
            'params' => [],
        ];

        $params['ArticleTypeSelect'] = [
            'method' => 'get',
            'uri' => '/backend/articletype-select',
            'params' => [],
        ];

        $params['ArticleTypeDetail'] = [
            'method' => 'get',
            'uri' => '/backend/articletype-detail',
            'params' => [
                'type_id'=>1
            ],
        ];

        $params['ArticleAdd'] = [
            'method' => 'post',
            'uri' => '/backend/article-add',
            'params' => [
                'type_id'=>1,
                'article_content'=>"content",
                'admin_id'=>"1",
                'article_title'=>"title",
            ],
        ];

        $params['ArticleEdit'] = [
            'method' => 'post',
            'uri' => '/backend/article-edit',
            'params' => [
                'article_id' => 1,
                'type_id'=>1,
                'article_content'=>"content",
                'admin_id'=>"1",
                'article_title'=>"title",
            ],
        ];

        $params['ArticleDelete'] = [
            'method' => 'post',
            'uri' => '/backend/article-delete',
            'params' => [
                'article_id' => 2,
            ],
        ];

        $params['ArticleList'] = [
            'method' => 'get',
            'uri' => '/backend/article-list',
            'params' => [],
        ];

        $params['ArticleDetail'] = [
            'method' => 'get',
            'uri' => '/backend/article-detail',
            'params' => [
                'article_id'=>1,
            ],
        ];
        return $params;
    }

    #类型添加
    public function testArticleTypeAdd() {
        $this->apiTest($this->params['ArticleTypeAdd']);
    }

    #类型查询
    public function testArticleTypeList() {
        $this->apiTest($this->params['ArticleTypeList']);
    }

    #类型下拉框查询
    public function testArticleTypeSelect() {
        $this->apiTest($this->params['ArticleTypeSelect']);
    }

    #类型更新
    public function testArticleTypeEdit() {
        $this->apiTest($this->params['ArticleTypeEdit']);
    }

    #类型详情
    public function testArticleTypeDetail() {
        $this->apiTest($this->params['ArticleTypeDetail']);
    }

    #文章添加
    public function testArticleAdd() {
        $this->apiTest($this->params['ArticleAdd']);
    }

    #文章修改
    public function testArticleEdit() {
        $this->apiTest($this->params['ArticleEdit']);
    }

    #文章删除
    public function testArticleDelete() {
        $this->apiTest($this->params['ArticleDelete']);
    }

    #文章列表
    public function testArticleList() {
        $this->apiTest($this->params['ArticleList']);
    }

    #文章详情
    public function testArticleDetail() {
        $this->apiTest($this->params['ArticleDetail']);
    }


}