<?php
/**
 * Created by PhpStorm.
 * User: fuyuehua
 * Date: 2017/9/13
 * Time: 11:00
 */
namespace Modules\Backend\Tests;

use Modules\Backend\Tests\Common\BackendTestCase;

class GoodsTest extends BackendTestCase
{

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->init();
    }

    public function readyApiParams()
    {
        $params['goods_add'] = [
            'method' => 'post',
            'uri' => '/backend/goods-add',
            'params' => [
                'goods' => '{"goods_info":{"goods_name":"\u5546\u54c13","cat_id":"1","brand_id":"2","type_id":"1","keywords":"\u5546\u54c12","goods_thumb":"\u5546\u54c13","goods_img":"\u5546\u54c14","shipping_range":"5","is_real":"1","is_shipping":"1","goods_desc":"\u5546\u54c1\u63cf\u8ff0"},"product_info":[{"attr":[{"attr_name":"\u989c\u8272","attr_value":"\u7ea2\u8272"},{"attr_name":"\u5c3a\u7801","attr_value":"L"}],"product_name":"\u8d27\u54c11","product_number":"1000","market_price":"2000","product_price":"3000","brand_desc":"\u8d27\u54c11\u63cf\u8ff0"},{"attr":[{"attr_name":"\u989c\u8272","attr_value":"\u7ea2\u8272"},{"attr_name":"\u5c3a\u7801","attr_value":"M"}],"product_name":"\u8d27\u54c12","product_number":"1000","market_price":"3000","product_price":"4000","brand_desc":"\u8d27\u54c12\u63cf\u8ff0"}]}',
            ],
        ];

        $params['goods_detail'] = [
            'method' => 'get',
            'uri' => '/backend/goods-detail',
            'params' => [
                'goods_id' => '1',
            ],
        ];

        $params['goods_list'] = [
            'method' => 'get',
            'uri' => '/backend/goods-list',
            'params' => [

            ],
        ];

        $params['goods_status_change'] = [
            'method' => 'post',
            'uri' => '/backend/goods-status-change',
            'params' => [
                'goods_id' => '1',
                'is_on_sale' => 1,
            ],
        ];

        $params['goods_edit'] = [
            'method' => 'post',
            'uri' => '/backend/goods-edit',
            'params' => [
                'goods' => '{"goods_info":{"goods_name":"\u5546\u54c13","goods_id":1,"cat_id":10,"brand_id":10,"type_id":1,"keywords":10,"goods_thumb":10,"goods_img":10,"shipping_range":10,"is_index":1,"is_real":1,"is_on_sale":1,"is_shipping":1,"sort":1,"goods_desc":10},"product_info":[{"attr":[{"attr_name":"\u989c\u8272","attr_value":"\u9ed1\u8272"},{"attr_name":"\u989c\u8272","attr_value":"\u9ed1\u8272"}],"product_id":1,"product_number":589,"market_price":2000,"product_price":3000,"brand_desc":3000,"is_show":1,"sort":1},{"attr":[{"attr_name":"\u989c\u8272","attr_value":"\u9ed1\u8272"},{"attr_name":"\u989c\u8272","attr_value":"\u9ed1\u8272"},{"attr_name":"\u989c\u8272","attr_value":"\u9ed1\u8272"}],"product_id":3,"product_number":589,"market_price":2000,"product_price":3000,"brand_desc":3000,"is_show":1,"sort":1},{"attr":[{"attr_name":"\u989c\u8272","attr_value":"\u9ed1\u8272"},{"attr_name":"\u989c\u8272","attr_value":"\u9ed1\u8272"},{"attr_name":"\u989c\u8272","attr_value":"\u9ed1\u8272"}],"product_id":0,"product_number":589,"market_price":2000,"product_price":3000,"brand_desc":3000}]}',
            ],
        ];

        $params['goods_delete'] = [
            'method' => 'post',
            'uri' => '/backend/goods-delete',
            'params' => [
                'goods_id' => '1',
            ],
        ];

        $params['goods_product_add'] = [
            'method' => 'post',
            'uri' => '/backend/goods-product-add',
            'params' => [
                'product_name' => '我的商品999',
                'goods_id' => '1',
                'product_number' => '1000',
                'market_price' => '123.32',
                'product_price' => '150.5',
                'attr' => '[{"attr_name":"\u989c\u8272","attr_value":"\u7ea2\u8272"},{"attr_name":"\u5c3a\u7801","attr_value":"L"}]',
            ],
        ];

        $params['goods_product_list'] = [
            'method' => 'get',
            'uri' => '/backend/goods-product-list',
            'params' => [

            ],
        ];

        $params['goods_product_status_change'] = [
            'method' => 'post',
            'uri' => '/backend/goods-product-status-change',
            'params' => [
                'product_id' => '1,2',
                'is_show' => 0
            ]
        ];

        $params['goods_product_edit'] = [
            'method' => 'post',
            'uri' => '/backend/goods-product-edit',
            'params' => [
                'product_name' => '我的商品999',
                'product_number' => '1',
                'market_price' => '123.32',
                'product_price' => '150.5',
                'product_id' => '1',
                'goods_id' => '1',
                'goods_color_value' => '',
                'brand_desc' => '',
                'is_show' => '1',
                'sort' => '0',
                'attr' => '[{"attr_id":1,"attr_name":"\u989c\u8272","attr_value":"\u9ed1\u8272"},{"attr_id":0,"attr_name":"\u989c\u8272","attr_value":"\u9ed1\u8272"}]',
            ],
        ];

        $params['goods_product_delete'] = [
            'method' => 'post',
            'uri' => '/backend/goods-product-delete',
            'params' => [
                'product_id' => '1',
            ],
        ];
        #商品品牌的添加
        $params['goodsbrand_add'] = [
            'method' => 'post',
            'uri' => '/backend/goodsbrand-add',
            'params' => [
                'brand_name' => 'apple',
                'brand_thumb' => '123',
                'brand_desc' => '123',
                'is_show'=>'1',
            ],
        ];
        #商品品牌的详情
        $params['goodsbrand_detail'] = [
            'method' => 'get',
            'uri' => '/backend/goodsbrand-detail',
            'params' => [
                'brand_id' => 1,
            ],
        ];
        #商品品牌的列表
        $params['goodsbrand_list'] = [
            'method' => 'get',
            'uri' => '/backend/goodsbrand-list',
            'params' => [

            ],
        ];
        #商品品牌的修改
        $params['goodsbrand_edit'] = [
            'method' => 'post',
            'uri' => '/backend/goodsbrand-edit',
            'params' => [
                'brand_id' => 1,
                'brand_name' => 'apple',
                'brand_thumb' => '123',
                'brand_desc' => '123',
                'is_show'=>'1',
            ],
        ];
        #商品品牌的删除
        $params['goodsbrand_delete'] = [
            'method' => 'post',
            'uri' => '/backend/goodsbrand-delete',
            'params' => [
                'brand_id' => 1,
            ],
        ];
        #商品分类的添加
        $params['goodscategory_add'] = [
            'method' => 'post',
            'uri' => '/backend/goodscategory-add',
            'params' => [
                'pid' => '0',
                'sort_order' => '123',
                'cat_name' => '123',
                'cat_desc'=>'1123',
                'cat_thumb'=>'123',
                'keywords'=>'123',
                'is_show'=>'1',
                'is_show_nav'=>'1',
            ],
        ];
        #商品分类的修改
        $params['goodscategory_edit'] = [
            'method' => 'post',
            'uri' => '/backend/goodscategory-edit',
            'params' => [
                'cat_id'=>1,
                'pid' => '0',
                'sort_order' => '123',
                'cat_name' => '123',
                'cat_desc'=>'1123',
                'cat_thumb'=>'123',
                'keywords'=>'123',
                'is_show'=>'1',
                'is_show_nav'=>'1',
            ],
        ];
        #商品分类的详情
        $params['goodscategory_detail'] = [
            'method' => 'get',
            'uri' => '/backend/goodscategory-detail',
            'params' => [
                'cat_id'=>1,
            ],
        ];
        #商品分类的树状列表结构
        $params['goodscategory_list_tree'] = [
            'method' => 'get',
            'uri' => '/backend/goodscategory-list-tree',
            'params' => [

            ],
        ];
        #商品分类的层级列表结构
        $params['goodscategory_list_level'] = [
            'method' => 'get',
            'uri' => '/backend/goodscategory-list-level',
            'params' => [

            ],
        ];
        #商品分类的删除
        $params['goodscategory_delete'] = [
            'method' => 'post',
            'uri' => '/backend/goodscategory-delete',
            'params' => [
                'cat_id'=>1,
            ],
        ];

        $params['goods_attribute_add'] = [
            'method' => 'post',
            'uri' => '/backend/attribute-add',
            'params' => [
                'attr_name' => 'attr_phpunit',
                'type_id'=>1,
            ],
        ];

        $params['goods_attribute_edit'] = [
            'method' => 'post',
            'uri' => '/backend/attribute-edit',
            'params' => [
                'attr_id'=>1,
                'type_id'=>1,
                'attr_name' => 'attr_phpunit_edit',
            ],
        ];

        $params['goods_attribute_del'] = [
            'method' => 'post',
            'uri' => '/backend/attribute-del',
            'params' => [
                'attr_id' => '1',
            ],
        ];

        $params['goods_attribute_list'] = [
            'method' => 'get',
            'uri' => '/backend/attribute-list',
            'params' => [
                'type_id'=>1,
            ],
        ];

        $params['goods_type_add'] = [
            'method' => 'post',
            'uri' => '/backend/type-add',
            'params' => [
                'type_name' => 'type_phpunit',
            ],
        ];

        $params['goods_type_edit'] = [
            'method' => 'post',
            'uri' => '/backend/type-edit',
            'params' => [
                'type_id'=>1,
                'type_name' => 'type_phpunit_edit',
            ],
        ];

        $params['goods_type_del'] = [
            'method' => 'post',
            'uri' => '/backend/type-del',
            'params' => [
                'type_id' => 1,
            ],
        ];

        $params['goods_type_list'] = [
            'method' => 'get',
            'uri' => '/backend/type-list',
            'params' => [],
        ];

        return $params;
    }

    public function testGoodsAdd()
    {
        $this->apiTest($this->params['goods_add']);
    }

    public function testGoodsDetail()
    {
        $this->apiTest($this->params['goods_detail']);
    }

    public function testGoodsList()
    {
        $this->apiTest($this->params['goods_list']);
    }

    public function testGoodsStatusChange()
    {
        $this->apiTest($this->params['goods_status_change']);
    }

    public function testGoodsEdit()
    {
        $this->apiTest($this->params['goods_edit']);
    }

    public function testGoodsProductAdd()
    {
        $this->apiTest($this->params['goods_product_add']);
    }

    public function testGoodsProductList()
    {
        $this->apiTest($this->params['goods_product_list']);
    }

    public function testGoodsProductStatusChange()
    {
        $this->apiTest($this->params['goods_product_status_change']);
    }

    public function testGoodsProductEdit()
    {
        $this->apiTest($this->params['goods_product_edit']);
    }

    public function testGoodsProductDelete()
    {
        $this->apiTest($this->params['goods_product_delete']);
    }

    public function testGoodsDelete()
    {
        $this->apiTest($this->params['goods_delete']);
    }
    /**
     * 品牌的添加
     * @Author CK
     */
    public function testGoodsBrandAddTest()
    {
        $this->apiTest($this->params['goodsbrand_add']);
    }
    /**
     * 品牌的详情
     * @Author CK
     */
    public function testGoodsBrandDetailTest()
    {
        $this->apiTest($this->params['goodsbrand_detail']);
    }
    /**
     * 品牌的列表
     * @Author CK
     */
    public function testGoodsBrandListTest()
    {
        $this->apiTest($this->params['goodsbrand_list']);
    }
    /**
     * 品牌的修改
     * @Author CK
     */
    public function testGoodsBrandEditTest()
    {
        $this->apiTest($this->params['goodsbrand_edit']);
    }
    /**
     * 品牌的删除
     * @Author CK
     */
    public function testGoodsBrandDeleteTest()
    {
        $this->apiTest($this->params['goodsbrand_delete']);
    }
    /**
     * 分类的添加
     * @Author CK
     */
    public function testGoodsCategoryAddTest()
    {
        $this->apiTest($this->params['goodscategory_add']);
    }
    /**
     * 分类的修改
     * @Author CK
     */
    public function testGoodsCategoryEditTest()
    {
        $this->apiTest($this->params['goodscategory_edit']);
    }
    /**
     * 分类的详情
     * @Author CK
     */
    public function testGoodsCategoryDetailTest()
    {
        $this->apiTest($this->params['goodscategory_detail']);
    }
    /**
     * 分类的树状列表
     * @Author CK
     */
    public function testGoodsCategoryListTreeTest()
    {
        $this->apiTest($this->params['goodscategory_list_tree']);
    }
    /**
     * 分类的层级列表
     * @Author CK
     */
    public function testGoodsCategoryListLevelTest()
    {
        $this->apiTest($this->params['goodscategory_list_level']);
    }
    /**
     * 分类的删除
     * @Author CK
     */
    public function testGoodsCategoryDeleteTest()
    {
        $this->apiTest($this->params['goodscategory_delete']);
    }

    public function testGoodsAttributeAdd() {
        $this->apiTest($this->params['goods_attribute_add']);
    }

    public function testGoodsAttributeEdit() {
        $this->apiTest($this->params['goods_attribute_edit']);
    }

    public function testGoodsAttributeDel() {
        $this->apiTest($this->params['goods_attribute_del']);
    }

    public function testGoodsAttributeList() {
        $this->apiTest($this->params['goods_attribute_list']);
    }

    public function testGoodsTypeAdd() {
        $this->apiTest($this->params['goods_type_add']);
    }

    public function testGoodsTypeEdit() {
        $this->apiTest($this->params['goods_type_edit']);
    }

    public function testGoodsTypeDel() {
        $this->apiTest($this->params['goods_type_del']);
    }

    public function testGoodsTypeList() {
        $this->apiTest($this->params['goods_type_list']);
    }
}